name: Publish Leertaken

on:
  release:
    types: [prereleased, released]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  windesheim-hbo-ict/leertaken

jobs:
  build-and-push-leertaken:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable containerd image store for docker
        uses: crazy-max/ghaction-setup-docker@v2
        with:
          version: v24.0.6
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            } 
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Push leertaken image
        run: docker build --push --platform linux/arm64,linux/amd64 --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }} --tag ghcr.io/${{ env.IMAGE_NAME }}:latest quartz/.

      - name: Cleanup docker images
        run: docker image prune -f -a
